//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OESK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OeskBenchmarkEntities : DbContext
    {
        public OeskBenchmarkEntities()
            : base("name=OeskBenchmarkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableCPU> TableCPU { get; set; }
        public virtual DbSet<TableFunction> TableFunction { get; set; }
        public virtual DbSet<TablePC> TablePC { get; set; }
        public virtual DbSet<TableRAM> TableRAM { get; set; }
        public virtual DbSet<TableTest> TableTest { get; set; }
        public virtual DbSet<TableText> TableText { get; set; }
    }
}
