//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableTest
    {
        public int IDTest { get; set; }
        public int IDPC { get; set; }
        public int IDFunction { get; set; }
        public int IDText { get; set; }
        public int NumberOfIterations { get; set; }
        public string FullTime { get; set; }
    
        public virtual TableFunction TableFunction { get; set; }
        public virtual TablePC TablePC { get; set; }
        public virtual TableText TableText { get; set; }
    }
}
