//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TablePC()
        {
            this.TableTest = new HashSet<TableTest>();
        }
    
        public int IDPC { get; set; }
        public int IDCPU { get; set; }
        public int IDRAM { get; set; }
    
        public virtual TableCPU TableCPU { get; set; }
        public virtual TableRAM TableRAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableTest> TableTest { get; set; }
    }
}
